package desktopapplication1;


import desktopapplication1.resources.TimerUpdate;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.Timer;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.KeyStroke;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * start_stop.java
 *
 * Created on Aug 31, 2011, 10:11:06 PM
 */
/**
 *
 * @author Philip
 */
public class start_stop extends javax.swing.JPanel {
    
    SimpleAudioRecorder sar;
    int num;
    String fileOpened;
    /** A return status code - returned if Cancel button has been pressed */
    public static final int RET_CANCEL = 0;
    /** A return status code - returned if OK button has been pressed */
    public static final int RET_OK = 1;
    private int returnStatus = RET_CANCEL;  
    
    JFrame container;
    /** Creates new form start_stop */
    public start_stop(int n, String f,JFrame contain) {
        initComponents();
        num=n;
        fileOpened=f;
        label1.setText("Recording Time: 00:00:00");
        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        container=contain;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okButton = new javax.swing.JButton();
        label1 = new java.awt.Label();
        cancelButton = new javax.swing.JButton();

        okButton.setLabel("Start Recording");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setText("label1");

        cancelButton.setEnabled(false);
        cancelButton.setLabel("Stop Recording");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cancelButton)
                        .addComponent(okButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        cancelButton.setEnabled(true);
        okButton.setEnabled(false);
        String temp=fileOpened.replaceAll("\\\\", "_");
        temp=temp.replaceAll(":", "_");
        sar= new SimpleAudioRecorder(System.getProperty("user.dir")+"\\projects\\audioFiles\\"+temp+(num+1)+".wav");
        Timer t = new Timer();
        long delay = 1000;
        t.schedule(new TimerUpdate(label1),0, delay );
}//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        
        cancelButton.setEnabled(false);
        okButton.setEnabled(true);
        sar.stopRecording();
        doClose(0);
}//GEN-LAST:event_cancelButtonActionPerformed

    private void closeDialog(java.awt.event.WindowEvent evt) {                             
        if(!okButton.isEnabled())
            sar.stopRecording();
        doClose(RET_CANCEL);
    }                            
    
    private void doClose(int retStatus) {
        
        returnStatus = retStatus;
        setVisible(false);
        container.dispose();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private java.awt.Label label1;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
}
